application:
  subdomain: lark
  multi_instance: true
  upstreams:
    - location: /
      backend: http://lark:8080/
  public_path:
    - /
  injects:
    - id: login-autofill
      when:
        - /login
        - /#login
      do:
        - src: builtin://simple-inject-password
          params:
            user: "{{ .U.admin_username }}"
            password: "{{ .U.admin_password }}"

services:
  lark:
    #  czyt/lark:v0.7.3
    image: registry.lazycat.cloud/czyt/czyt/lark:da9d0bf7549dbd6d
    environment:
      - LARK_PORT=8080
      - LARK_DATA_DIR=/app/data
      - LARK_FRONTEND_ORIGIN=*
      # 数据库配置 - 根据类型选择
      - LARK_DB_TYPE={{.U.db_type}}
      - LARK_DB_DSN={{.U.db_dsn}}
      # 管理员设置（首次运行时使用）
      - LARK_ADMIN_USERNAME={{.U.admin_username}}
      - LARK_ADMIN_PASSWORD={{.U.admin_password}}
      - LARK_ADMIN_NICKNAME={{.U.admin_nickname}}
      # 音乐库目录（根据用户选择使用外部目录或默认目录）
      - LARK_LIBRARY_DIR=/lzcapp/run/mnt/home/{{ .U.library_dir }}
    binds:
      - /lzcapp/var/data:/app/data

ext_config:
  enable_media_access: true
  enable_document_access: true
  permissions:
    - PERM_MEDIA_MOUNT_SHARED
