package: community.lazycat.app.lark
version: 0.8.11
name: Lark
description: "A music library and streaming application"
min_os_version: 1.5.0
author: czyt
homepage: https://github.com/czyt/lark
license: MIT

locales:
  zh:
    name: "百灵音乐"
    description: "音乐库管理与流媒体播放应用"
  en:
    name: "Lark Music"
    description: "Music library management and streaming application"

permissions:
  required:
    - net.internet
    - document.read
    - document.private
